import { Button } from "@/components/ui/button";
import { Sparkles, BarChart2 } from "lucide-react";

export default function AIAnalysis() {
  return (
    <section id="ai-analysis" className="py-24 overflow-hidden">
      <div className="w-[1440px] max-w-full mx-auto px-6 lg:px-14">
        <div className="grid lg:grid-cols-2 gap-16 items-center">
          <div className="space-y-8 order-2 lg:order-1">
            <div className="inline-flex items-center rounded-full border border-purple-500/30 bg-purple-500/10 px-3 py-1 text-sm font-medium text-purple-600">
              <Sparkles className="mr-2 h-4 w-4" />
              AI Market Intelligence
            </div>
            <h2 className="font-heading text-3xl font-bold tracking-tight sm:text-4xl">
              AI That Explains the Market <br /> — Not Just Numbers
            </h2>
            <div className="space-y-4 text-lg text-muted-foreground leading-relaxed">
              <p>
                Farmgreene’s AI tools analyze historical and real-time price
                data to generate clear summaries, trend insights, and long-term
                outlooks. Instead of manually interpreting charts, users can
                quickly understand what’s happening—and why.
              </p>
            </div>
            <ul className="space-y-3">
              <li className="flex items-center gap-3">
                <div className="h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/50 flex items-center justify-center text-green-600 text-xs font-bold">
                  ✓
                </div>
                <span className="font-medium">Price trend summaries</span>
              </li>
              <li className="flex items-center gap-3">
                <div className="h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/50 flex items-center justify-center text-green-600 text-xs font-bold">
                  ✓
                </div>
                <span className="font-medium">Seasonal pattern analysis</span>
              </li>
              <li className="flex items-center gap-3">
                <div className="h-6 w-6 rounded-full bg-green-100 dark:bg-green-900/50 flex items-center justify-center text-green-600 text-xs font-bold">
                  ✓
                </div>
                <span className="font-medium">
                  Natural-language market reports
                </span>
              </li>
            </ul>
            <Button
              size="lg"
              className="rounded-full bg-purple-600 hover:bg-purple-700 text-white mt-4"
            >
              See AI Reports in Action
            </Button>
          </div>

          {/* Visual Mockup */}
          <div className="order-1 lg:order-2 bg-slate-900 rounded-3xl p-6 md:p-8 shadow-2xl skew-y-1 transform transition-transform hover:skew-y-0 duration-500">
            <div className="flex items-center gap-4 mb-6 border-b border-slate-700 pb-4">
              <div className="h-10 w-10 rounded-full bg-purple-500/20 text-purple-400 flex items-center justify-center">
                <Sparkles className="h-5 w-5" />
              </div>
              <div>
                <div className="text-white font-bold">Maize Market Outlook</div>
                <div className="text-xs text-slate-400">
                  Generated by Farmgreene AI • Just now
                </div>
              </div>
            </div>
            <div className="space-y-4">
              <div className="h-32 bg-slate-800 rounded-xl relative overflow-hidden">
                <div className="absolute inset-x-0 bottom-0 h-20 bg-gradient-to-t from-green-500/20 to-transparent"></div>
                {/* Abstract Chart Line */}
                <svg
                  className="absolute inset-0 w-full h-full text-green-500"
                  preserveAspectRatio="none"
                >
                  <path
                    d="M0 100 Q 50 80 100 90 T 200 60 T 300 80 T 400 30"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                  />
                </svg>
              </div>
              <div className="space-y-2">
                <div className="h-2 w-3/4 bg-slate-700 rounded animate-pulse"></div>
                <div className="h-2 w-full bg-slate-700 rounded animate-pulse delay-75"></div>
                <div className="h-2 w-5/6 bg-slate-700 rounded animate-pulse delay-150"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
