import type { Metadata } from "next";
import {
  LegalLayout,
  LegalSection,
  LegalList,
  LegalLink,
  LegalNote,
} from "@/components/marketing/legal/LegalLayout";
import {
  CONTROLLER,
  LAST_UPDATED,
} from "@/components/marketing/legal/legal-details";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "The terms you agree to when you use Farmgreene — what the platform does, what it deliberately doesn't do, and where responsibility sits.",
};

const sections = [
  { id: "who-we-are", label: "Who you're dealing with" },
  { id: "accounts", label: "Your account" },
  { id: "prices", label: "The price data" },
  { id: "ai", label: "Written analysis" },
  { id: "marketplace", label: "The marketplace" },
  { id: "money", label: "Money" },
  { id: "owners", label: "If you list equipment" },
  { id: "agents", label: "If you collect prices" },
  { id: "conduct", label: "What you agree not to do" },
  { id: "content", label: "Your content" },
  { id: "availability", label: "Early access" },
  { id: "liability", label: "Liability" },
  { id: "ending", label: "Ending it" },
  { id: "law", label: "Governing law" },
];

export default function TermsPage() {
  return (
    <LegalLayout
      kicker="Terms"
      title="The agreement, in"
      accent="plain words"
      lede="Using Farmgreene means agreeing to this. It's written to be read rather than skimmed past, and the parts that matter most to you are the ones about money and equipment."
      updated={LAST_UPDATED}
      sections={sections}
    >
      <LegalSection id="who-we-are" heading="Who you're dealing with">
        <p>
          Farmgreene is not a registered company. It is built and operated by{" "}
          {CONTROLLER.name} in {CONTROLLER.country}, as an individual. When you
          agree to these terms, that is who you are agreeing with. If and when
          Farmgreene is incorporated, this page will be updated to name the
          company.
        </p>
        <p>
          We mention it up front because it affects what recourse you have, and
          you're entitled to know that before you rely on the platform.
        </p>
      </LegalSection>

      <LegalSection id="accounts" heading="Your account">
        <LegalList
          items={[
            "You must be 18 or older.",
            "Give accurate details, and keep them accurate.",
            "Your password is yours to protect. Anything done through your account is treated as done by you.",
            "One person, one account. Accounts created to work around limits may be removed.",
            "Tell us promptly if you think someone else has got into your account.",
          ]}
        />
      </LegalSection>

      <LegalSection id="prices" heading="The price data">
        <p>
          Prices on Farmgreene are recorded by a person visiting a market and
          writing down what was being asked that day, then reviewed before
          publication. That's a real observation — it is not a quotation, an
          offer, or a guarantee that anyone will trade at that number.
        </p>
        <p>
          Markets move, quality varies, and a price seen in one market on one
          morning may not hold in the next market or the next week. Use the data
          as evidence, not as a promise.
        </p>
        <LegalNote>
          Nothing on Farmgreene is financial, investment or trading advice.
          Decisions you make about buying, selling or holding your produce are
          yours.
        </LegalNote>
      </LegalSection>

      <LegalSection id="ai" heading="Written analysis">
        <p>
          Some of the commentary — the daily brief and the per-crop analysis — is
          generated by software from the approved price data, and it carries the
          sources it drew on. It is there to save you reading a table, not to
          tell you what to do.
        </p>
        <p>
          Generated text can be wrong or misleading even when the underlying
          numbers are right. Where it matters, check it against the prices
          themselves, which are always shown.
        </p>
      </LegalSection>

      <LegalSection id="marketplace" heading="The marketplace">
        <p>
          Farmgreene introduces people who own equipment to people who want to
          rent it. That is the whole of what it does. The rental agreement itself
          is between the two of you, and we are not a party to it.
        </p>
        <p>Specifically, we do not:</p>
        <LegalList
          items={[
            "Inspect equipment, or verify that it is in the condition described.",
            "Guarantee that an owner actually owns what they've listed. We check the document submitted, which is not the same thing.",
            "Guarantee that a renter will collect, pay, or return a machine in the state they got it.",
            "Insure anything, or cover damage, injury or loss.",
            "Take part in disputes between you, though you're welcome to tell us when something goes wrong.",
          ]}
        />
        <p>
          Listings are reviewed before they appear publicly. That review is a
          check for obvious problems, not an endorsement.
        </p>
      </LegalSection>

      <LegalSection id="money" heading="Money">
        <LegalNote>
          Farmgreene never takes, holds, processes or refunds payment. There is
          no payment system in the platform at all.
        </LegalNote>
        <p>
          Rates, deposits, operator charges and delivery fees are recorded with a
          rental request so that both sides have the same record of what was
          agreed. Paying it, collecting it, and refunding it all happen directly
          between renter and owner, by whatever means you arrange.
        </p>
        <p>
          This means you carry the risk of non-payment or non-return yourself.
          Agree terms you're comfortable with, and prefer people you can verify.
        </p>
        <p>
          Using Farmgreene is currently free. If that changes, you'll be told
          well in advance and nothing will start charging you automatically.
        </p>
      </LegalSection>

      <LegalSection id="owners" heading="If you list equipment">
        <LegalList
          items={[
            "List only equipment you actually own or are authorised to rent out.",
            "Describe it honestly, including its faults. Photographs should be of the actual machine.",
            "The ownership document you upload must be genuine.",
            "Keep your availability current, and respond to requests rather than leaving people waiting.",
            "You set your own rates and terms, and you accept or decline every request yourself.",
            "You are responsible for meeting whatever legal, safety and insurance obligations apply to your machinery.",
          ]}
        />
        <p>
          Listings that misrepresent equipment, or that use documents belonging
          to someone else, are removed and the account closed.
        </p>
      </LegalSection>

      <LegalSection id="agents" heading="If you collect prices">
        <p>
          Agent accounts are not currently open. When they are, agents will be
          expected to submit only prices they have personally observed, at the
          market and on the date recorded.
        </p>
        <p>
          Invented or copied submissions undermine the one thing this platform
          is for, and will end the arrangement immediately. Submissions are
          reviewed before they count toward any published figure.
        </p>
      </LegalSection>

      <LegalSection id="conduct" heading="What you agree not to do">
        <LegalList
          items={[
            "Scrape, bulk-download or resell the price data.",
            "Submit false prices, fake listings, or documents that aren't yours.",
            "Use the platform to arrange anything unlawful.",
            "Attempt to break, overload, or get unauthorised access to the service.",
            "Impersonate anyone, or misrepresent who you're acting for.",
            "Harass or defraud other users.",
          ]}
        />
      </LegalSection>

      <LegalSection id="content" heading="Your content">
        <p>
          What you upload stays yours. You give us permission to store and
          display it as far as running the service requires — showing your
          listing photographs to people browsing the marketplace, for instance.
        </p>
        <p>
          Ownership and insurance documents are never displayed publicly. They
          are used for review only. Delete your listing and we stop displaying
          its content.
        </p>
        <p>
          Approved price submissions are an exception: they become part of the
          historical record and stay in it. They describe a crop, a market and a
          date rather than a person.
        </p>
      </LegalSection>

      <LegalSection id="availability" heading="Early access">
        <p>
          Farmgreene is early. Features change, occasionally break, and
          occasionally disappear. There is no uptime commitment and no support
          guarantee — when you write in, one person reads it and replies as soon
          as he can.
        </p>
        <p>
          Keep your own records of anything that matters to you. Don't rely on
          Farmgreene as your only copy of anything.
        </p>
      </LegalSection>

      <LegalSection id="liability" heading="Liability">
        <p>
          The service is provided as it is. To the fullest extent Nigerian law
          allows, we are not liable for losses arising from your use of it —
          including trading decisions made on the basis of price data, disputes
          with other users, equipment that isn't as described, money that isn't
          paid, or data that is unavailable or lost.
        </p>
        <p>
          Nothing here limits liability that cannot lawfully be limited, such as
          liability for fraud or for death or personal injury caused by
          negligence.
        </p>
      </LegalSection>

      <LegalSection id="ending" heading="Ending it">
        <p>
          You can stop using Farmgreene and ask for your account to be deleted at
          any time. We can suspend or close an account that breaks these terms,
          and we will say why unless there's a good reason not to.
        </p>
      </LegalSection>

      <LegalSection id="law" heading="Governing law">
        <p>
          These terms are governed by the laws of the Federal Republic of
          Nigeria, and disputes fall to the Nigerian courts.
        </p>
        <p>
          Questions about any of this go to{" "}
          <LegalLink href={`mailto:${CONTROLLER.email}`} external>
            {CONTROLLER.email}
          </LegalLink>{" "}
          or the{" "}
          <LegalLink href="/contact">contact page</LegalLink>. See also our{" "}
          <LegalLink href="/privacy">privacy policy</LegalLink>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
